<a href="https://colab.research.google.com/github/aamirrajput/Github-Aameri/blob/main/intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [50]:
a = [1, 2, 3, 4, 5]
print(a)

[1, 2, 3, 4, 5]


In [51]:
print('hello aamir')

hello aamir


In [73]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import scipy

handle arrays(1D, 2D, 3D)

ID array

1. np.array: array consist of several numbers
2. np.linspace: array of series from strat value to end value, with specific incerment.
3. np.arange: array of seires between two values with specfic.


In [74]:
# Create array with specified values
array1 = np.array([10, 11, 45, 75, 65, 78, 90, 85, 56, 77])
print(array1)

# create  an array, say from 1 to 50 with specified increment say 5
array2 = np.arange(1, 50, 5)
print(array2)

# create a 1D numpy array consisting of numbers from 1 to 100, divided uniformly
array3 = np.linspace(1, 100, 10)
print(array3)

[10 11 45 75 65 78 90 85 56 77]
[ 1  6 11 16 21 26 31 36 41 46]
[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


print the length of each array

In [76]:
np.array([10, 20, 30, 40, 50])

array([10, 20, 30, 40, 50])

In [75]:
np.arange(10, 100, 5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [56]:
new_array = np.arange(0, 25, 0.5)

for i in range(len(new_array)):
  print(new_array[i])


0.0
0.5
1.0
1.5
2.0
2.5
3.0
3.5
4.0
4.5
5.0
5.5
6.0
6.5
7.0
7.5
8.0
8.5
9.0
9.5
10.0
10.5
11.0
11.5
12.0
12.5
13.0
13.5
14.0
14.5
15.0
15.5
16.0
16.5
17.0
17.5
18.0
18.5
19.0
19.5
20.0
20.5
21.0
21.5
22.0
22.5
23.0
23.5
24.0
24.5


print the length of array

In [57]:
print(len(array1))
print(len(array2))
print(len(array3))


10
10
10


instead repertivitve codes, we can use for loop

In [58]:
arrays = np.array([array1, array2, array3])

for i in range(len(arrays)):
  print(len(arrays[i]))

10
10
10


In [59]:
new_array = np.arange(0, 25, 0.5)

for i in range(len(arrays)):
  print(new_array[i])

0.0
0.5
1.0


Now, instead the element in the array in ascending order (smallest to highest)

In [60]:
print('sorted from smallest to highest:', np.sort(array1))

sorted from smallest to highest: [10 11 45 56 65 75 77 78 85 90]


To sort with descending order, we can use alternative([::-1])

In [61]:
print('Sorted from higest to smallest:', array1[::-1])

Sorted from higest to smallest: [77 56 85 90 78 65 75 45 11 10]


Numpy array is unique because indexing starts from 0, nor 1. Try printing the first element of the array 

In [62]:
print('first element N:', array1[-1])
print('last element N-1:', array1[-2])


first element N: 77
last element N-1: 56


In [63]:
print('first element:', array1[0])
print('second element:', array1[1])
print('last eight element of the array:', array1[-8])


first element: 10
second element: 11
last eight element of the array: 45


In [64]:
new_array[-2]

24.0

In [65]:
new_array[-10]

20.0

In [66]:
print('fifth until eighth element:', array1[5:8])

fifth until eighth element: [78 90 85]


print the last four element in the array 

In [67]:
print('last four element:', array1[-4:])


last four element: [90 85 56 77]


2D array (Matrix)

in math we know 2D array as a matrix, we create matrix also using np.array

In [68]:
new_array

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5,
       11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. ,
       16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5, 21. , 21.5,
       22. , 22.5, 23. , 23.5, 24. , 24.5])

In [69]:
new_array[3:6]

array([1.5, 2. , 2.5])

In [70]:
#each row as a 1D array
first = np.array([10, 20, 30])
second = np.array([50, 70, 90])
third = np.array([12, 14, 16])

#stack them togehter into 2D array 
M = np.array([first,
              second,
              third])
M

array([[10, 20, 30],
       [50, 70, 90],
       [12, 14, 16]])

OR, You can build it directly
you already know how to make 1D numpy array by np.array([...]). There's only one squared bracket. So for a matrix, which is a 2D numpy array
([...]) with two aquared brackets.

In [71]:
M = np.array([[10, 20, 30],
              [50,70,90],
              [12, 14, 16]])
M

array([[10, 20, 30],
       [50, 70, 90],
       [12, 14, 16]])

Remember that python indexing start from 0. if you want to print the element M1.1, pass M[0,0]


In [77]:
print('Element 1,1:', M[0,2])

Element 1,1: 30


Likewise, Print element M 1,3

In [78]:
print('Element 1,3:', M[0,2])

Element 1,3: 30


In [79]:
print('All element in second row:', M[1,:])

All element in second row: [50 70 90]


Print all elements in column 2 or element Mn,2

In [80]:
print('All element in second column:', M[:,1])

All element in second column: [20 70 14]


Data Cleansing

Create an array consist of NAN values with np.nan

In [81]:
my_array = np.array([np.nan, 15, np.nan, 20, np.nan, 34, np.nan, np.nan, 67, 30, 10])

Check if there is value in an array. Return Ture if there's any.Useless, it's return False(Boolean values)

In [82]:
np.isnan(my_array).any()

True

Remove NAN values from array(just delete the NAN value)

In [84]:
nan_remove = my_array[~np.isnan(my_array)]
nan_remove

array([15., 20., 34., 67., 30., 10.])

Replaceing (inputing) NAN values with mean of data numbers.

In [89]:
#replace number of zeros

#first make a new array to store the inputed data, name it new array
new_array = np.array(my_array)

#replace with zero
new_array[np.isnan(new_array)]=100
new_array

array([100.,  15., 100.,  20., 100.,  34., 100., 100.,  67.,  30.,  10.])

Imputing NAN values with the mean of the data 

In [88]:
np.mean(new_array)

16.0