<a href="https://colab.research.google.com/github/aamirrajput/Github-Aameri/blob/main/intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
a = [1, 2, 3, 4, 5]
print(a)

[1, 2, 3, 4, 5]


In [ ]:
print('hello aamir')

hello aamir


In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import scipy

handle arrays(1D, 2D, 3D)

ID array

1. np.array: array consist of several numbers
2. np.linspace: array of series from strat value to end value, with specific incerment.
3. np.arange: array of seires between two values with specfic.


In [22]:
# Create array with specified values
array1 = np.array([10, 11, 45, 75, 65, 78, 90, 85, 56, 77])
print(array1)

# create  an array, say from 1 to 50 with specified increment say 5
array2 = np.arange(1, 50, 5)
print(array2)

# create a 1D numpy array consisting of numbers from 1 to 100, divided uniformly
array3 = np.linspace(1, 100, 10)
print(array3)

[10 11 45 75 65 78 90 85 56 77]
[ 1  6 11 16 21 26 31 36 41 46]
[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


In [2]:
np.array([10, 20, 30, 40, 50])

array([10, 20, 30, 40, 50])

In [6]:
np.arange(10, 100, 5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [ ]:
new_array = np.arange(0, 25, 0.5)

for i in range(len(new_array)):
  print(new_array[i])


In [17]:
print('sorted from smalllest to highest:', np.sort(array):

SyntaxError: ignored